---

- hosts: all
  become: true
  gather_facts: true
  tasks:

  - name: install updates ( CEntos )
    yum:
      update_only: true
      update_cache: true
    when: ansible_distribution == "CentOS"

  - name: Install updates ( UBUNTU )
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"

