---

- hosts: all
  become: true
  gather_facts: true
  pre_tasks:

  - name: Crete user simone
    tags: always
    user:
      name: simone
      groups: root

  - name: add ssh key for  us
    tags: always
    authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC11ZDI1NTE5AAAAIKOLfR1E/3MRE0pHGay00tUP1G23NOGwUEBzgoF29OoZ Ansible_new"

  - name: add sudoers file for Simone use
    tags: always
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440
